version: 2.1

orbs:
  tfsec: mycodeself/tfsec@1.1.0

jobs:
  tfsec-tests:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: infrastructure
          exclude-checks: GEN001,GCP001,GCP002
  terraform-init:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: cd infrastructure && terraform init
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-validate:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            cd infrastructure  \
            && terraform validate \
            && terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  #  tests-workflow:
  #    jobs:
  #      - tfsec-tests
  terraform-workflow:
    jobs:
      - terraform-init
      - terraform-validate
