version: 2.1

orbs:
  tfsec: mycodeself/tfsec@1.1.0
  go: circleci/go@1.7.3

jobs:
  tfsec-tests:
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: infrastructure
          exclude-checks: GEN001,GCP001,GCP002
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-init:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: cd infrastructure && terraform init -input=false
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-validate:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Validate && Plan
          command: |
            cd infrastructure  \
            && terraform validate \
            && terraform plan -out tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-apply:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Terraform Apply
          command: cd infrastructure && terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  infrastructure-test:
    docker:
      - image: cimg/go:1.21.4
    steps:
      - attach_workspace:
          at: .
      - run:
          name: cd
          command: |
            cd test
            go infrastructure-test.go
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform-destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Destroy Terraform Infrastructure
          command: cd infrastructure && terraform destroy -auto-approve

workflows:
  terraform-workflow:
    jobs:
      - terraform-init
      - terraform-validate:
          requires:
            - terraform-init
      - approve-terraform-apply:
          type: approval
          requires:
            - terraform-validate
      - terraform-apply:
          requires:
            - approve-terraform-apply
      - approve-infrastructure-test:
          type: approval
          requires:
            - terraform-apply
      - infrastructure-test:
          requires:
            - approve-infrastructure-test
      - approve-terraform-destroy:
          type: approval
          requires:
            - terraform-apply
      - terraform-destroy:
          requires:
            - approve-terraform-destroy
