# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  tfsec: mycodeself/tfsec@1.1.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
    tfsec-tests:
      executor: tfsec/default
      steps:
        - checkout
        - tfsec/scan:
            directory: infrastrucuture
            exclude-checks: GEN001,GCP001,GCP002
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests-workflow:
    jobs:
      - tfsec-tests
